#this file tells NGinx how to handle incoming requests
server {  #web server block 
    listen 80; #default http port, so when someone visits the site, nginx listens
    location / {
        root /usr/share/nginx/html; #this tells nginx that react build files are located here, so basically when you run nopm run build, react created files which then get copied to thi s usr path inside the nginx container
        index index.html; #when someones visits http://site.com/ nginx loads index.html - react file entrypoint
        try_files $uri /index.html; #if someone entrs a url page after the slash that doesn't exist then a s=message shows to lead  them back to index.html
    }

    location /api/ { #this block catches api requests
        proxy_pass http://backend:3000/; #forwards request to backend container ex: http://site.com/api/login nginx sends it to http://backend:3000/login where backend is the docker container name amd 3000 is port 
        proxy_set_header Host $host; #passes original host header to backend
        proxy_set_header X-Real-IP $remote_addr; #sends real user IP to backend, otherwise backend would see nginx ip    
    }
}